version: '2'
volumes:
    ${VOLUME_DB}:
        external: true
    ${VOLUME_ARQUIVOSEXTERNOS}:
        external: true
    ${VOLUME_SOLR}:
        external: true
    ${VOLUME_CERTS}:
        external: true
    ${VOLUME_FONTES}:
        external: true
        
services:
    storage-arquivosexternos:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - ${VOLUME_ARQUIVOSEXTERNOS_MOUNT}:/dados:rw
    
    storage-fontes:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - ${VOLUME_FONTES_MOUNT}:/opt:rw
    
    storage-certs:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - ${VOLUME_CERTS_MOUNT}:/certs:rw
                
    #jod: #servicejod
    #    image: ${DOCKER_IMAGE_JOD} #servicejod

    memcached:
        image: ${DOCKER_IMAGE_MEMCACHED}

    db:
        image: ${DOCKER_IMAGE_BD}
        labels:
            io.rancher.container.pull_image: always
            io.rancher.sidekicks: storage-db
        volumes:
            - ${VOLUME_DB}:${DB_DATA_DIRECTORY}
            
  
    solr:
        image: ${DOCKER_IMAGE_SOLR}
        environment:
            - VIRTUAL_HOST=http://${APP_HOST}/solr*,https://${APP_HOST}/solr*
            - FORCE_SSL=true
        volumes:
            - ${VOLUME_SOLR}:${SOLR_DATA_DIRECTORY}
        
    
    app-atualizador:
        image: ${DOCKER_IMAGE_APP}
        entrypoint: "/entrypoint-atualizador.sh"
        volumes_from:
            - storage-arquivosexternos
            - storage-fontes
            - storage-certs
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.start_once: 'true'
        environment:
        - APP_PROTOCOLO=${APP_PROTOCOLO}
        - APP_HOST=${APP_HOST}
        - APP_ORGAO=${APP_ORGAO}
        - APP_ORGAO_DESCRICAO=${APP_ORGAO_DESCRICAO}
        - APP_NOMECOMPLEMENTO=${APP_NOMECOMPLEMENTO}
        - APP_DB_TIPO=${APP_DB_TIPO}
        - APP_DB_PORTA=${APP_DB_PORTA}
        - APP_DB_SIP_BASE=${APP_DB_SIP_BASE}
        - APP_DB_SIP_USERNAME=${APP_DB_SIP_USERNAME}
        - APP_DB_SIP_PASSWORD=${APP_DB_SIP_PASSWORD}
        - APP_DB_SEI_BASE=${APP_DB_SEI_BASE}
        - APP_DB_SEI_USERNAME=${APP_DB_SEI_USERNAME}
        - APP_DB_SEI_PASSWORD=${APP_DB_SEI_PASSWORD}
        - APP_DB_ROOT_USERNAME=${APP_DB_ROOT_USERNAME}
        - APP_DB_ROOT_PASSWORD=${APP_DB_ROOT_PASSWORD}
        - APP_SIP_CHAVE_ACESSO=${APP_SIP_CHAVE_ACESSO}
        - APP_SEI_CHAVE_ACESSO=${APP_SEI_CHAVE_ACESSO}
        - MODULO_ESTATISTICAS_INSTALAR=${MODULO_ESTATISTICAS_INSTALAR}
        - MODULO_ESTATISTICAS_VERSAO=${MODULO_ESTATISTICAS_VERSAO}
        - MODULO_ESTATISTICAS_URL=${MODULO_ESTATISTICAS_URL}
        - MODULO_ESTATISTICAS_SIGLA=${MODULO_ESTATISTICAS_SIGLA}
        - MODULO_ESTATISTICAS_CHAVE=${MODULO_ESTATISTICAS_CHAVE}
        - MODULO_WSSEI_INSTALAR=${MODULO_WSSEI_INSTALAR}
        - MODULO_WSSEI_VERSAO=${MODULO_WSSEI_VERSAO}
        - MODULO_WSSEI_URL_NOTIFICACAO=${MODULO_WSSEI_URL_NOTIFICACAO}
        - MODULO_WSSEI_ID_APP=${MODULO_WSSEI_ID_APP}
        - MODULO_WSSEI_CHAVE=${MODULO_WSSEI_CHAVE}
        links:
        - db:db
        - memcached:memcached
        - solr:solr
        #- jod:jod #servicejod
    app:
        image: ${DOCKER_IMAGE_APP}
        entrypoint: "/entrypoint.sh"
        #ports:
        #    - ${APP_PORTA_80_MAP}
        #    - ${APP_PORTA_443_MAP}
        volumes_from:
            - storage-arquivosexternos
            - storage-fontes
            - app-atualizador
            - storage-certs
        labels:
            io.rancher.container.pull_image: always
            io.rancher.sidekicks: storage-arquivosexternos,storage-fontes,app-atualizador    
        environment:
        - APP_PROTOCOLO=${APP_PROTOCOLO}
        - APP_HOST=${APP_HOST}
        - APP_ORGAO=${APP_ORGAO}
        - APP_ORGAO_DESCRICAO=${APP_ORGAO_DESCRICAO}
        - APP_NOMECOMPLEMENTO=${APP_NOMECOMPLEMENTO}
        - APP_DB_TIPO=${APP_DB_TIPO}
        - APP_DB_PORTA=${APP_DB_PORTA}
        - APP_DB_SIP_BASE=${APP_DB_SIP_BASE}
        - APP_DB_SIP_USERNAME=${APP_DB_SIP_USERNAME}
        - APP_DB_SIP_PASSWORD=${APP_DB_SIP_PASSWORD}
        - APP_DB_SEI_BASE=${APP_DB_SEI_BASE}
        - APP_DB_SEI_USERNAME=${APP_DB_SEI_USERNAME}
        - APP_DB_SEI_PASSWORD=${APP_DB_SEI_PASSWORD}
        - APP_DB_ROOT_USERNAME=${APP_DB_ROOT_USERNAME}
        - APP_DB_ROOT_PASSWORD=${APP_DB_ROOT_PASSWORD}
        - APP_SIP_CHAVE_ACESSO=${APP_SIP_CHAVE_ACESSO}
        - APP_SEI_CHAVE_ACESSO=${APP_SEI_CHAVE_ACESSO}
        - MODULO_ESTATISTICAS_INSTALAR=${MODULO_ESTATISTICAS_INSTALAR}
        - MODULO_ESTATISTICAS_VERSAO=${MODULO_ESTATISTICAS_VERSAO}
        - MODULO_ESTATISTICAS_URL=${MODULO_ESTATISTICAS_URL}
        - MODULO_ESTATISTICAS_SIGLA=${MODULO_ESTATISTICAS_SIGLA}
        - MODULO_ESTATISTICAS_CHAVE=${MODULO_ESTATISTICAS_CHAVE}
        - MODULO_WSSEI_INSTALAR=${MODULO_WSSEI_INSTALAR}
        - MODULO_WSSEI_VERSAO=${MODULO_WSSEI_VERSAO}
        - MODULO_WSSEI_URL_NOTIFICACAO=${MODULO_WSSEI_URL_NOTIFICACAO}
        - MODULO_WSSEI_ID_APP=${MODULO_WSSEI_ID_APP}
        - MODULO_WSSEI_CHAVE=${MODULO_WSSEI_CHAVE}
        - VIRTUAL_HOST=https://${APP_HOST}/sei*,https://${APP_HOST}/sip*,https://${APP_HOST}/infra*,http://${APP_HOST}/sei*,http://${APP_HOST}/sip*,http://${APP_HOST}/infra*
        #- EXCLUDE_PORTS=443
        #- EXCLUDE_PORTS=80
        #- EXTRA_ROUTE_SETTINGS=ssl verify none
        - COOKIE=SRV insert indirect nocache
        links:
        - db:db
        - memcached:memcached
        - solr:solr
        #- jod:jod #servicejod
    #balanceador:
    #    image: dockercloud/haproxy
    #    links:
    #        - app
    #        - solr
    #    environment:
    #        - EXTRA_FRONTEND_SETTINGS_80=use_backend stats if { path_beg -i /haproxy }, acl is_root path -i /, redirect code 301 location http://${APP_HOST}/sei/ if is_root
    #        - EXTRA_FRONTEND_SETTINGS_443=use_backend stats if { path_beg -i /haproxy }, acl is_root path -i /, redirect code 301 location http://${APP_HOST}/sei/ if is_root
    #        - CERT_FOLDER=/certs
    #    volumes_from:
    #        - storage-certs
    #    volumes:
    #        - /var/run/docker.sock:/var/run/docker.sock
    #    ports:
    #        - ${BALANCEADOR_PORTA_80_MAP}
    #        - ${BALANCEADOR_PORTA_443_MAP}