version: '2'
volumes:
    local-storage-db:
        external: true
    local-arquivosexternos-storage:
        external: true
    local-volume-solr:
        external: true
    local-certs-storage:
        external: true
    local-fontes-storage:
        external: true
        
services:
    storage-arquivosexternos:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - local-arquivosexternos-storage:/dados:rw
    
    storage-fontes:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - local-fontes-storage:/opt:rw
    
    storage-certs:
        image: "busybox:latest"
        labels:
            io.rancher.container.start_once: "true"
        volumes:
            - local-certs-storage:/certs:rw
                
    #jod: #servicejod
    #    image: processoeletronico/vagrant-sei4_jod #servicejod

    memcached:
        image: memcached

    db:
        image: processoeletronico/sei4-mysql5.7:1.0
        labels:
            io.rancher.container.pull_image: always
            io.rancher.sidekicks: storage-db
        volumes:
            - local-storage-db:/var/lib/mysql
            
  
    solr:
        image: processoeletronico/sei4-solr8.2.0:1.0
        environment:
            - VIRTUAL_HOST=http://sou.cristao.jesus.br/solr*,https://sou.cristao.jesus.br/solr*
            - FORCE_SSL=true
        volumes:
            - local-volume-solr:/dados
        
    
    app-atualizador:
        image: processoeletronico/sei4-app:1.1.0
        entrypoint: "/entrypoint-atualizador.sh"
        volumes_from:
            - storage-arquivosexternos
            - storage-fontes
            - storage-certs
        labels:
            io.rancher.container.pull_image: always
            io.rancher.container.start_once: 'true'
        environment:
        - APP_PROTOCOLO=https
        - APP_HOST=sou.cristao.jesus.br
        - APP_ORGAO=ME
        - APP_ORGAO_DESCRICAO="Orgao Processo Eletronico - MySql"
        - APP_NOMECOMPLEMENTO="SEI - PEN - DTH"
        - APP_DB_TIPO=MySql
        - APP_DB_PORTA=3306
        - APP_DB_SIP_BASE=sip
        - APP_DB_SIP_USERNAME=sip_user
        - APP_DB_SIP_PASSWORD=sip_user
        - APP_DB_SEI_BASE=sei
        - APP_DB_SEI_USERNAME=sei_user
        - APP_DB_SEI_PASSWORD=sei_user
        - APP_DB_ROOT_USERNAME=root
        - APP_DB_ROOT_PASSWORD=root
        - APP_SIP_CHAVE_ACESSO=d27791b8b33226ca19662539e9eb77edf604bd61d7f51c28f1f6387bb8413d1d9f0960d5
        - APP_SEI_CHAVE_ACESSO=7babf862dd3c172174e8e81ae7559e81a11ba933a3ddbb979eb9e56bc7d424603179ff17
        - MODULO_ESTATISTICAS_INSTALAR=true
        - MODULO_ESTATISTICAS_VERSAO=CompatibilidadeSEI4.0.0
        - MODULO_ESTATISTICAS_URL=https://estatistica.dev.processoeletronico.gov.br
        - MODULO_ESTATISTICAS_SIGLA=SEIPUBLICO
        - MODULO_ESTATISTICAS_CHAVE=seipublico
        - MODULO_WSSEI_INSTALAR=
        - MODULO_WSSEI_VERSAO=
        - MODULO_WSSEI_URL_NOTIFICACAO=
        - MODULO_WSSEI_ID_APP=
        - MODULO_WSSEI_CHAVE=
        links:
        - db:db
        - memcached:memcached
        - solr:solr
        #- jod:jod #servicejod
    app:
        image: processoeletronico/sei4-app:1.1.0
        entrypoint: "/entrypoint.sh"
        #ports:
        #    - 80:80
        #    - 443:443
        volumes_from:
            - storage-arquivosexternos
            - storage-fontes
            - app-atualizador
            - storage-certs
        labels:
            io.rancher.container.pull_image: always
            io.rancher.sidekicks: storage-arquivosexternos,storage-fontes,app-atualizador    
        environment:
        - APP_PROTOCOLO=https
        - APP_HOST=sou.cristao.jesus.br
        - APP_ORGAO=ME
        - APP_ORGAO_DESCRICAO="Orgao Processo Eletronico - MySql"
        - APP_NOMECOMPLEMENTO="SEI - PEN - DTH"
        - APP_DB_TIPO=MySql
        - APP_DB_PORTA=3306
        - APP_DB_SIP_BASE=sip
        - APP_DB_SIP_USERNAME=sip_user
        - APP_DB_SIP_PASSWORD=sip_user
        - APP_DB_SEI_BASE=sei
        - APP_DB_SEI_USERNAME=sei_user
        - APP_DB_SEI_PASSWORD=sei_user
        - APP_DB_ROOT_USERNAME=root
        - APP_DB_ROOT_PASSWORD=root
        - APP_SIP_CHAVE_ACESSO=d27791b8b33226ca19662539e9eb77edf604bd61d7f51c28f1f6387bb8413d1d9f0960d5
        - APP_SEI_CHAVE_ACESSO=7babf862dd3c172174e8e81ae7559e81a11ba933a3ddbb979eb9e56bc7d424603179ff17
        - MODULO_ESTATISTICAS_INSTALAR=true
        - MODULO_ESTATISTICAS_VERSAO=CompatibilidadeSEI4.0.0
        - MODULO_ESTATISTICAS_URL=https://estatistica.dev.processoeletronico.gov.br
        - MODULO_ESTATISTICAS_SIGLA=SEIPUBLICO
        - MODULO_ESTATISTICAS_CHAVE=seipublico
        - MODULO_WSSEI_INSTALAR=
        - MODULO_WSSEI_VERSAO=
        - MODULO_WSSEI_URL_NOTIFICACAO=
        - MODULO_WSSEI_ID_APP=
        - MODULO_WSSEI_CHAVE=
        - VIRTUAL_HOST=https://sou.cristao.jesus.br/sei*,https://sou.cristao.jesus.br/sip*,https://sou.cristao.jesus.br/infra*,http://sou.cristao.jesus.br/sei*,http://sou.cristao.jesus.br/sip*,http://sou.cristao.jesus.br/infra*
        #- EXCLUDE_PORTS=443
        - EXCLUDE_PORTS=80
        - EXTRA_ROUTE_SETTINGS=ssl verify none
        - COOKIE=SRV insert indirect nocache
        links:
        - db:db
        - memcached:memcached
        - solr:solr
        #- jod:jod #servicejod
    balanceador:
        image: dockercloud/haproxy
        links:
            - app
            - solr
        environment:
            - EXTRA_FRONTEND_SETTINGS_80=use_backend stats if { path_beg -i /haproxy }, acl is_root path -i /, redirect code 301 location http://sou.cristao.jesus.br/sei/ if is_root
            - EXTRA_FRONTEND_SETTINGS_443=use_backend stats if { path_beg -i /haproxy }, acl is_root path -i /, redirect code 301 location http://sou.cristao.jesus.br/sei/ if is_root
            - CERT_FOLDER=/certs
        volumes_from:
            - storage-certs
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 80:80
            - 443:443
